# Generated by Django 5.0 on 2023-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('sector', models.TextField()),
                ('topic', models.TextField()),
                ('insight', models.TextField()),
                ('url', models.URLField()),
                ('region', models.TextField()),
                ('start_year', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.TextField()),
                ('relevance', models.IntegerField()),
                ('pestle', models.TextField()),
                ('source', models.TextField()),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
