# Generated by Django 5.0 on 2023-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='added',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='end_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='impact',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='insight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='intensity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='likelihood',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='pestle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='region',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='sector',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='start_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='topic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
